# Generated by Django 5.1 on 2024-11-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('industry_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='meetingorganizer',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting'),
        ),
        migrations.AlterField(
            model_name='meetingorganizer',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.student'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizers',
            field=models.ManyToManyField(blank=True, through='meetings.MeetingOrganizer', to='meetings.organizer'),
        ),
        migrations.AddField(
            model_name='meetingorganizer',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.organizer'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingorganizer',
            unique_together={('meeting', 'organizer')},
        ),
    ]
