# Generated by Django 5.1 on 2024-11-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_organizer_alter_meetingorganizer_meeting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingorganizer',
            name='student',
        ),
        migrations.AlterField(
            model_name='meetingorganizer',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.organizer'),
        ),
    ]
