# Generated by Django 5.1 on 2024-12-08 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_mandatory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
