# Generated by Django 5.1 on 2024-12-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='mandatory',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='industry_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['date', 'mandatory'], name='meeting_date_mandatory_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingorganizer',
            index=models.Index(fields=['meeting', 'organizer'], name='meeting_organizer_idx'),
        ),
        migrations.AddIndex(
            model_name='organizer',
            index=models.Index(fields=['industry_type'], name='organizer_industry_idx'),
        ),
    ]
